# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

 branches:
   include:
     - main

pool:
  name: 'SelfHostedVM'

steps:

- task: CopyFiles@2
  inputs:
    SourceFolder: '.'
    Contents: '**.html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/html'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Resume.html'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- script: dir $(Build.ArtifactStagingDirectory)/html
  displayName: 'Verify extracted files'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure PayAsYouGo (90f2a80e-6934-46d8-9b29-95402af7c21c)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
            $storageAccountName = "aronresumestore"
            $containerName = "$web"
            $sourceFolder = "$(Build.ArtifactStagingDirectory)/html"
      
            az storage blob upload-batch `
                --destination $containerName `
                --source $sourceFolder `
                --account-name $storageAccountName `
                --auth-mode login
      
            Write-Host "Upload complete!"





