# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

 branches:
   include:
     - main

pool:
  name: 'SelfHostedVM'

steps:

- task: CopyFiles@2
  inputs:
    SourceFolder: '.'
    Contents: '**.html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/html'


- task: PowerShell@2
  displayName: 'Verify extracted files'
  inputs:
    targetType: 'inline'
    script: 'Get-ChildItem -Path "$(Build.ArtifactStagingDirectory)/html" -Recurse'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure PayAsYouGo (90f2a80e-6934-46d8-9b29-95402af7c21c)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
            $storageAccountName = "aronresumestore"
            $containerName = "'$web"
            $sourceFolder = "$(Build.ArtifactStagingDirectory)/html"

            Write-Host "Uploading files from: $sourceFolder"
      
            az storage blob upload-batch `
                --destination $containerName `
                --source $sourceFolder `
                --account-name $storageAccountName `
                --auth-mode login
      
            Write-Host "Upload complete!"





